### ISSUE TITLE
Not generating Gatsby nodes

### ISSUE THREAD

**Issue by jamesdbruner** [Unobvious-Technology/gatsby-plugin-source-amazon-wishlist#3]
Like the title says, I'm having trouble generating nodes. I'm getting this `warning The gatsby-source-amazon-wishlist plugin has generated no Gatsby nodes. Do you need it?` in my terminal and I checked in graphiql and confirmed that there's no nodes created in there.

This is what my `gatsby-config.js` looks like 
```
{
      resolve: 'gatsby-source-amazon-wishlist',
      options: {
        wishlistUrl: 'https://www.amazon.com/registry/wishlist/1R66VUOR7WC9P',
        language: 'en-US',
        limit: 25,
      },
    },
```

I'm on gatsby v2.4.4 and node v11.14.0, any ideas why this would be the case?

**Comment by ThisIsMissEm** [comment]
Hi! Honestly, this was just built as a bit of a hack project and hasn't been touched in months, so chances are it's not compatible with Gatsby anymore.
